apiVersion: v1
kind: ConfigMap
metadata:
  name: ems-dev-config
  namespace: employee-dev
data:
  APP_MODE: "Development"
  FLASK_ENV: "development"
  FEATURE_DEBUG: "true"
  API_URL: "http://backend.employee-dev.svc.cluster.local:5000"
  LOG_LEVEL: "DEBUG"
  DATABASE_URL: "sqlite:///./backend/instance/dev.db"
