apiVersion: v1
kind: Secret
metadata:
  name: ems-dev-secret
  namespace: employee-dev
stringData:
  JWT_SECRET_KEY: "DevSecretKey123!"
  ADMIN_PASSWORD: "ChangeMe123!"
  ADMIN_USERNAME: "admin"
  API_KEYS: "dev-api-key-ems"
