apiVersion: v1
kind: Secret
metadata:
  name: ems-prod-secret
  namespace: employee-prod
stringData:
  JWT_SECRET_KEY: "Prod$ecureKey!2026"
  ADMIN_PASSWORD: "ProdAdmin!2026"
  ADMIN_USERNAME: "prod_admin"
  API_KEYS: "prod-api-key-ems"
