apiVersion: v1
kind: Secret
metadata:
  name: ems-uat-secret
  namespace: employee-uat
stringData:
  JWT_SECRET_KEY: "UatSecretKey!2026"
  ADMIN_PASSWORD: "UATSecurePass!"
  ADMIN_USERNAME: "uat_admin"
  API_KEYS: "uat-api-key-ems"
