apiVersion: v1
kind: Secret
metadata:
  name: ems-qa-secret
  namespace: employee-qa
stringData:
  JWT_SECRET_KEY: "QaSecretKey!2026"
  ADMIN_PASSWORD: "QA123Secure!"
  ADMIN_USERNAME: "qa_admin"
  API_KEYS: "qa-api-key-ems"
